### PR TITLE
Text overflow issue fixed

### LINKED ISSUE #42: Unable to access actions from top bar dropdown when project name and dapp titles are too long
## Description
Unable to access _Edit DApp configuration_, _Download_ and _Delete_ buttons when project name and dapp titles are too long

## Steps to reproduce
1. Create a new project by accessing the top menu bar and clicking _Create New_
2. Set project name to `mmmmmmmmmmmmmmmmmmmm` or any other "lengthy" name
3. Set dapp title to `mmmmmmmmmmmmmmmmmmmm` or any other "lengthy" name
4. Confirm with `Next`
5. Choose any template e.g. Empty Project
6. Click _Create Project_
7. Open the top menu bar again

## Expected result
Expected to be able to access all the project actions regardless of the project name or dapp title length.

## Actual result
studio-issue-long

### PR DESCRIPTION
**Pull request by waheed25**
this closes #42

### CODE REVIEW

**Comment by javier-tarazaga** [comment]
@waheed25 I think this is introducing a regression when the project text is short. 

screen shot 2018-08-31 at 16 53 06

**Comment by samia-khalil** [comment]
oh, width causing the problem here will fix it.

**Comment by waheed25** [comment]
oh, width causing problem here. I will fix it.

**Comment by filippsen** [comment]
To complement Javier's comment, here is the previous behavior for reference:

studio-issue-regression

Also, considering the current implementation (new-ux), I expected the hyphen "-" to always be present and for it to be followed by the dapp title right afterwards. The way it is now is not consistent in my view:

studio-issue-hypen-missing

**Comment by waheed25** [comment]
screen shot 2018-09-03 at 10 35 58 am
here is fixture i just change width to max-width

**Comment by filippsen** [comment]
@waheed25 The regression pointed out by @javier-tarazaga is fixed, but the hyphen "problem" reported in my previous comment is still present.

**Comment by javier-tarazaga** [comment]
Yeap, I can see still the issue in the screenshot provided. Also make sure the ... only appears when the text is a lot closer to the buttons (right now there is a huge gap between the ... and the icons)

**Comment by filippsen** [comment]
@javier-tarazaga I was about to share the same.
studio-issue-85

**Pull request merged**
