### PR TITLE
Add Chainlink template

### PR DESCRIPTION
**Pull request by thodges-gh**
### Description of the Change

Adds Chainlink template to Superblocks Lab. 

### Benefits

Users can easily create and deploy externally-aware smart contracts by utilizing the Chainlink network.

### Possible Drawbacks

Within the Lab's Browser environment, it is not possible to obtain full functionality. It is recommended that users select the Ropsten test network for optimal compatibility. Rinkeby and Kovan can be supported with minimal changes.

### Verification Process

I was not able to verify that this works locally due to the linked issue below.

### Github Issues

https://github.com/SuperblocksHQ/superblocks-lab/issues/259

### CODE REVIEW

**Comment by futurejones** [comment]
Having Templates in zip form is not a viable option as the the source code is not viewable and can not be reviewed or tested.

**Comment by thodges-gh** [comment]
@futurejones: @Bashlund told me via email to use the downloaded zip file in a PR to get the Chainlink templates added. Please let me know what I should do if that is not correct. Thank you.

**Comment by futurejones** [comment]
@thodges-gh this comment is not directed at you. What you have done is the right thing for the existing template format i.e. Templates are in zips.
I am saying that this needs to be changed so that the source code is visible.

**Comment by thodges-gh** [comment]
@futurejones Got it, thank you! I made [this](https://github.com/thodges-gh/superblocks-chainlink-template) repo to show the source.

**Comment by futurejones** [comment]
@thodges-gh great, thanks.

**Comment by Bashlund** [comment]
Hey, thanks for the template @thodges-gh ! Great work! I think @filippsen is on his way to try this out in the coming days :)
Yes you are right @futurejones, the zip format is suboptimal. It used to be in a `json` format, which was (for me at least) even more weird to work with. Now I can at least open the zip in my editor (Vim) and inspect the files, even modify and save them. But it doesn't lend it self to a smooth development cycle, indeed.
Maybe we should file an issue about this so we can collect some pro's and con's of different ways of handling it? :)

**Comment by thodges-gh** [comment]
Thank you @filippsen! The original zip was that which was exported directly from the lab. I just changed that to come from a zipped archive extracted from my project and updated the contract to reflect Chainlink's master.

**Comment by filippsen** [comment]
@thodges-gh
I updated my previous comment to match the latest changes (commit c66e22ec). Notable mentions are: a) to consider supporting other networks and adding a reference "app" (items 3b and 3c. They could be related, if applicable); b) to add the template to the list of available templates.

Other than that, I also noticed the following, after inspecting the latest changes:

1. _Zip_ file now contains the `.git` directory;
2. The _app_ directory is missing (not part of the _zip_ file anymore). Was that intentional ?
3. `newRun` calls in `MyContract.sol` were modified. This was apparently to reflect the changes to `Chainlinked` contract, correct ?

The contract is still working on _Ropsten_:

- Deployment. OK
```
Creator:
0x...
Contract address:
0x...
Age: ...
Origin: Superblocks Lab
Block #...
Gas used: 3277022
```

- `requestEthereumPrice(2216dd2bf5464687a05ded0b844e200c, USD)`. OK
```
From:
0x...
To:
0x...
Value: 0 ether
Age: ...
Origin: Superblocks Lab
Block #...
Gas used: 164774
```

- `currentPrice` returns `uint256 10694`. OK

Thank you!

**Comment by javier-tarazaga** [comment]
Gonna close this PR. As we are moving towards the cloud there is no need to hardcode templates in the source code any longer. We could take this one later and include Chainlink's projects as featured in a explore projects collection.

**Pull request closed without merging**
