### PR TITLE
Change Transactions History view size

### PR DESCRIPTION
**Pull request by waheed25**
this closes#88

### CODE REVIEW

**Comment by waheed25** [comment]
This might be the issue with interact window because it works fine for like compile deploy and some other windows.
I also observed same bug in **Mosaic-view**.
The **mouseup** and **mousemove** functions are not fires when mouse out of trans-view and mousedown already fired then whenever mouse goes outside of event trigging area and current window is **interact-window** or **Mosaic-view** this issue will occurs.

**Comment by waheed25** [comment]
@filippsen After some investigation i found the problem with iframe that is placed in **contractInteraction** component **onmousemove** function not works when mouse is on the area of iframe this works well if we disable pointer events from css like this **pointer-events: none;.**

**Comment by filippsen** [comment]
@waheed25 That is apparently working now.

Found another rendering bug, which I'm not sure when it was added since the transactions were added only recently. The transaction "badges" only resize together with the container width until a certain point. After that, it looks like this:
lab-issue-156-ff

**Comment by waheed25** [comment]
@filippsen I don't think i have change anything related transaction "badges" this could be the natural behaviour before the implementation of resizing of trans-view.

**Comment by filippsen** [comment]
@waheed25 Since this request deals with resizable container width I would consider necessary to do that adjustment, yes. Otherwise it doesn't look consistent.

I do see the content layout changes when resizing (2 columns), but then if that is a problem we should file a new issue and fix it on a separate moment. Thank you!

**Comment by waheed25** [comment]
@filippsen then i think my last commit make a consistent view according to resizing of window.

**Pull request merged**
